### ISSUE TITLE
Suggestion - Lore

### ISSUE THREAD

**Issue by GGEasyMan** [HealPotion/EnchantmentsEnhance#3]
Add an option when upgrading the item, change the lore that is in the config.

E.g:

14:
suffix: "+14"
    lore:
      WEAPON:
         - Damage: 90
15:
suffix: "+15"
    lore:
      WEAPON:
         - Damage: 100

This will change the lore of the item.

**Comment by HealPotion** [comment]
Your suggestion is taken and has been implemented in the latest commit.
